config/routes.rb
Railsyard2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => "site#show"
  themes_for_rails
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}
  
  match "/login" => redirect("/users/login")
  match "/logout" => redirect("/users/logout")
  match "/signup" => redirect("/users/signup")
  match "/admin" => redirect("/admin/pages")
  
  namespace :admin do 
    resources :pages do
      put 'sort', :on => :collection
      put 'set_editing_language', :on => :collection
      post 'toggle', :on => :member
      post 'apply_template', :on => :member
      put 'apply_layout', :on => :member
      get 'purge_limbo', :on => :member
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :users do
      post 'toggle', :on => :member
    end
    resources :articles do
      post 'toggle', :on => :member
    end
    resources :article_layouts do
      put 'apply_layout', :on => :member
      put 'set_editing_language', :on => :collection
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :categories do
      post 'quick_create', :on => :collection
    end
    resource :settings
    resources :uploads
    resources :comments do
      post 'toggle', :on => :member
    end
    resources :tags, :only => [:index]
  end
  
  resources :users
  resources :comments
  match ':lang/article/:year/:month/:day/:pretty_url' => 'articles#show', :as => 'show_article', :constraints => {:lang => $AVAILABLE_LANGUAGES, :year => /\d+/, :month => /\d+/, :day => /\d+/}
  match ':lang/feed' => 'articles#feed', :as => :feed, :defaults => { :format => 'atom' }

  match '/:lang' => "site#show", :constraints => {:lang => /[a-z]{2}/}
  scope "/:lang" do
    match "*page_url" => "site#show", :constraints => {:lang => /[a-z]{2}/}
  end
  
  

end

app/views/admin/pages/_available_snippets.html.erb
<div class="wrap cell_11 available_widgets">
    <header>
        <h2>
           <%= t "admin.snippets.snippets_available_to_drag_in_areas" %>
        </h2>           
    </header>
    <% snippets_available.map do |snip| %>
        <div class="area_box">
            <h2><%= snip["name"] %></h2>
            <section id="<%= snip["class"] %>" class='drag_source'>
                <% snip["actions"].map do |act| %>    
                    <div class="available_widget sortable_item drag_item" id="<%= snip["class"] %>%<%= act["method"] %>" data-snipid="<%= snip["class"] %>%<%= act["method"] %>">
                        <header>
                            <h2><%= act["name"] %></h2>
                        </header>
                        <a href="#" class="icon grabber">&nbsp;</a>
                        <a href="#" class="toggle toggle_closed">&nbsp;</a>
                        <div class="toggle_container" style="display:none;">                  
                            <div class="block">
                                <p><%= act["desc"] %></p>
                            </div>
                        </div>
                    </div>
                <% end %>
            </section>
        </div>
    <% end %>
</div>

app/views/admin/pages/_drag_drop.js.erb
$(document).ready(function() {
    
    // Drag and drop of snippets to areas
    // drag_item(s) are the 'source' snippets on the right, items available to be dropped inside areas. drag_source is the container.
    $('.drag_item','.drag_source').draggable({ // This means every drag_item inside drag_source
        handle:'.grabber',  // The element which is used to 'grab' the item
        items:'div.wrap', // The item to be sorted when grabbed!
        connectToSortable: '.drop_target', // Link to the drop destination
        helper:'clone' // Clone the item when dragged instead of moving it
    });
    
    // This sets the unique id to the cloned snippet
	// WARNING this function runs two times.. still wondering why. TO-DO fix it running just one time
    $('.drop_target').livequery(function(){
	
         $(this).droppable("destroy");
         $(this).droppable({
              drop: function(event, ui) {
                  var dropped = ui.draggable;
                  if (dropped.hasClass('drag_item')){ // ui.draggable is the dragged item just dropped
                    time = new Date().getTime();
                    newid = dropped.data('snipid') + '%' + time;
					dropped.attr('id', newid); // ok works
					//dropped.data('snipid', newid); // not working - why?
					//jQuery.data(dropped, 'snipid', newid); // still not working
					dropped.attr('data-snipid', newid); // ok works
                    dropped.removeClass("drag_item");
                    dropped.removeClass("available_widget");
                    dropped.removeClass("ui-draggable");
                    dropped.addClass("wrap");
                  };
              }
         });
    });
    
    // Provides both the creation and the sorting of snippets, submitting the list of snippets present in every area
    $('.drop_target').sortable({
        items:'.sortable_item',
        forceHelperSize:true,
        placeholder: 'dashed_placeholder',        
        forcePlaceholderSize:true,
        connectWith: '.drop_target',
        stop: function(event, ui){
            var sortorder={};
            $('.drop_target').each(function(){
                var itemorder=$(this).sortable('toArray');
                var targetId=$(this).attr('id');
                sortorder[targetId] = itemorder.toString();
            });
            $.ajax({
                type: 'put',
                url: '<%= sorting_url %>',
                data: ({'areas':sortorder}),
                // complete: function(response) {
                //     console.debug(response);
                // }
            });
        } 
    });
    
    $("#layout_form").change(function () {
        var selection = "";
        $("#layout_form option:selected").each(function () {
            selection += $(this).attr('value');
        });
        if (confirm('<%= t("admin.layouts.layout_change_confirm") %>'))
            $.ajax({
                type: "put",
                url: '<%= apply_layout_url %>',
                data: "selected_layout="+selection,
                // success: function(response) {
                //     console.debug(response);
                // }
            });
        return false;
    });

}); // $(document).ready()

app/views/admin/pages/_form.html.erb
<div class="wrap block">
     <div class="">  
         <div class="block">
             <%= f.label :title, t('admin.general.title') %>
             <%= f.text_field :title, {:id=>"title", :title=>"Page title, can\'t be blank", :class=>"full required"} %>

             <%= f.label :subtitle, t('admin.pages.subtitle') %>
             <%= f.text_field :subtitle, {:id=>"subtitle", :title=>"Page subtitle, can be blank", :class=>"full"} %>

             <fieldset class="group">
                <legend><%= t('admin.pages.page_options') %></legend>
                <div class="cell_8">
                    <div class="input_group">
                        <% visible_in_menu_checked = page.visible_in_menu || page.visible_in_menu.nil? %>
                        <%= f.check_box :visible_in_menu, :checked => visible_in_menu_checked %> <%= t "admin.general.visible_in_menu" %><br/>
                        <% published_checked = page.published || page.published.nil? %>
                        <%= f.check_box :published, :checked => published_checked %> <%= t "admin.general.published" %><br/>
                        <%= f.check_box :reserved %> <%= t "admin.general.reserved" %>
                    </div>
                </div>
                <div class="cell_8">
                    <label><%= t "admin.layouts.layout" %></label><%= f.select :layout_name, options_from_collection_for_select(@layouts.map, 'filename', 'title', @current_layout.filename) %>
                    <p>Changing layout makes all the current snippets on page to be moved to the Limbo.</p>
                </div>
             </fieldset>
        </div>
    </div>    
</div>

<div class="wrap block">
    <ul class="content_accordion no_header">
        <li>
            <a href="#" class="handle">&nbsp;</a>
            <h3 class="bar"><%= t('admin.pages.advanced_options') %></h3>
            <div class="content">
                <%= f.label t('admin.general.pretty_url') %>
                <%= f.text_field :pretty_url, {
                    :title => t("admin.pages.hint_pretty_url"),
                    :class => "medium"
                } %>

                <%= f.label 'Meta Title' %>
                <%= f.text_field :meta_title, {
                    :title => t("admin.pages.hint_meta_title"),
                    :class => "full"
                } %>

                <%# TODO inserire testi help nella form pagina %>
                <%= f.label 'Meta Keywords' %>
                <%= f.text_area :meta_keywords, {
                    :title => t("admin.pages.hint_meta_keywords"),
                    :class => "large"
                } %>

                <%= f.label 'Meta Description' %>
                <%= f.text_area :meta_description, {
                    :title => t("admin.pages.hint_meta_description"),
                    :class => "large"
                } %>
                
                <%= f.label :featured_image, t('admin.general.featured_image') %>
                <%= f.file_field :featured_image %>

                <%= f.label 'Content div id' %>
                <%= f.text_field :div_id, {
                    :title => t("admin.pages.hint_div_id")
                } %>

                <%= f.label 'Content div class' %>
                <%= f.text_field :div_class, {
                    :title => t("admin.pages.hint_div_class")
                } %>

                <%= f.label 'Content div style' %>
                <%= f.text_field :div_style, {
                    :title => t("admin.pages.hint_div_style")
                } %>

                <%= f.label 'Javascript' %>
                <%= f.text_area :script, { :size => "110x20",
                    :title => t("admin.pages.hint_javascript")
                } %>
            </div>
        </li>
    </ul>
</div>    

<script type="text/javascript"> 
    var title = new LiveValidation('title');
    title.add( Validate.Presence );
    
    // var realemail = new LiveValidation('realemail');
    // realemail.add( Validate.Email );
    // var atleast = new LiveValidation('atleast');
    // atleast.add( Validate.Length, { minimum: 30 } );
</script>

app/views/admin/pages/_item.html.erb
<tr id='page_item_<%= item.id %>'>
    <td>
        <%= link_to item.title, edit_admin_page_path(item) %>
    </td>
    <td>
        <%= l item.updated_at, :format => :date_with_parenthesized_time %>
    </td>
    <td calss="center">
        <%= item.reserved ? t("admin.general.yes") : t("admin.general.no") %>
    </td>
    <td class="center">
        <%= item.published ? (link_to t("admin.general.yes"), toggle_admin_page_path(item), :remote => true, :method => :post, :html => {:class => 'icon-v'}) : (link_to t("admin.general.no"), toggle_admin_page_path(item), :remote => true, :method => :post, :html => {:class => 'icon-x'}) %>
    </td>
    <td class="center">
        <%= link_to image_tag("../admin/images/icons/small/grey/Properties.png"), edit_admin_page_path(item) %>
        <%= link_to image_tag("../admin/images/icons/small/grey/Pencil.png"), admin_page_path(item) %>
        <%= link_to image_tag("../admin/images/icons/small/grey/View.png"), get_yard_url(item) %>
    </td>
</tr>

app/views/admin/pages/_layout_selector.html.erb
<div class="wrap cell_11">
    <header>
        <h2><%= t "admin.layouts.layout" %></h2>
    </header>
    <p class="cell_9 omega"><%= t "admin.layouts.changing_layout" %></p>
    <form id='layout_form' class="cell_7 alpha">
        <%= select_tag "layout", options_from_collection_for_select(layouts, 'identifier', 'title', current_layout.identifier) %>
    </form>
</div>

app/views/admin/pages/_menu.html.erb
<nav id="top_bar" class="clearfix  round_top">
    <ul class="clearfix">
        <%# TODO fare helper per verifica del path in cui sono %>
        <li<%= " class='current'" if controller.controller_name == "pages" and controller.action_name == "index" %>>
            <%= link_to( image_tag("/admin/images/icons/small/white/List.png") + t('admin.pages.lages_list'), admin_pages_url() )%>
        </li>
        <li<%= " class='current'" if controller.controller_name == "pages" and controller.action_name == "new" %>>
            <%= link_to( image_tag("/admin/images/icons/small/white/Pencil.png") + t('admin.pages.new_page'), new_admin_page_path() )%>
        </li>
        <li <%= " class='current'" if controller.controller_name == "pages" and controller.action_name == "tree" %>>
            <%= link_to( image_tag("/admin/images/icons/small/white/List%20w_%20Images.png") + t('admin.pages.pages_tree'), tree_admin_pages_path() )%>
        </li>
    </ul>
</nav>
<%# TODO correggere il link menu che punta all'albero delle pagine %>

app/views/admin/pages/_snippet_in_area.html.erb
<div class="wrap active_widget sortable_item" id="<%= snip.handler %>" data-snipid="<%= snip.handler %>" >
    <header>
        <h2><%= truncate(snip.title, :length => 20, :omission => '...') %></h2>        
    </header>
    <% if controller.controller_name == "article_layouts" %>
        <a href="#" class="icon grabber">&nbsp;</a>
        <%= link_to "edit", edit_admin_article_layout_snippet_path(snip.article_layout.id, snip.id), :class=>"icon edit" %>
        <%= link_to '<span>remove</span>'.hs, admin_article_layout_snippet_path(snip.article_layout.id, snip.id), :method => :delete, :confirm => t('admin.pages.are_you_sure_to_delete', :name => snip.title), :class => 'icon delete' %>
    </ul>
    <% else %>
        <a href="#" class="icon grabber">&nbsp;</a>
        <%= link_to "<span>edit</span>".hs, edit_admin_page_snippet_path(snip.page.id, snip.id), :class=>"icon edit" %>
        <%= link_to '<span>delete</span>'.hs, admin_page_snippet_path(snip.page.id, snip.id), :method => :delete, :confirm => t('admin.pages.are_you_sure_to_delete', :name => snip.title), :class => 'icon delete' %>
    <% end %>
    <a href="#" class="toggle toggle_closed icon info">&nbsp;</a>
    <div class="toggle_container" style="display:none;">                  
        <div class="block">
            <p><%= snip.description %></p>
        </div>
    </div>
</div>

app/views/admin/pages/edit.html.erb
<%= content_for :title do %><%= t('admin.pages.edit_page', :title => @page.title) %><% end %>

<header class="page_description">
  <h2>[<%= @page.lang %>] <%= t('admin.pages.edit_page', :title => @page.title) %> - <%= link_to t("admin.pages.go_to_page_contents"), admin_page_path(@page), :class=>"button" %></h2>
</header>

<div class="wrap cell_16">
    <% unless @page.errors.blank? %>
    <div class="alert alert_red">
        <img height="24" width="24" src="/admin/images/icons/small/white/Alarm%20Bell.png">
        <%= t('admin.general.errors') %>: <%= errors_for @page %>
    </div>
    <% end %>
    
    <%= form_for @page, :url => admin_page_path(@page), :html => { :multipart => true } do |f| %>
        <%= render :partial => "form", :object => @page, :as => :page, :locals => {:f => f, :lang => @admin_editing_language} %>
        <div class="buttons">
            <%= link_to t('admin.general.delete'), admin_page_url(@page), :method => :delete, :confirm => t('admin.pages.are_you_sure_to_delete', :name => @page.title), :class => "submit delete"  %>
            <%= link_to t('admin.general.back'), admin_pages_url, :class => "submit" %>
            <%= submit_tag t('admin.general.save'), :class => "submit" %>    
            <%= submit_tag t('admin.general.save_and_close'), :class => "submit", :name => 'save_and_close' %>  
        </div>
    <% end %>
</div>

app/views/admin/pages/index.html.erb
<%= content_for :extra_header do %>
    <link rel="stylesheet" type="text/css" href="/admin/stylesheets/pages_tree.css" media="screen">
<% end %>
<%= content_for :title do %><%= t('admin.pages.pages_management') %><% end %>

<div class="lang_selector">
    <%= select_tag "language", options_from_collection_for_select(Language.all, 'short', 'name', @admin_editing_language),
        :onchange => "$.post('#{set_editing_language_admin_pages_path}', {'_method':'put', 'admin_editing_language':this.value} );" %>    
</div>


<header class="page_description">
    <h2><%= t('admin.pages.pages_list') %></h2>
</header>

<div class="wrap cell_16 round_all">
    <table class="fancy_rows datatable">
        <thead>
            <tr>
                <th><%= t('admin.general.title') %></th> 
                <th><%= t('admin.general.last_update') %></th> 
                <th><%= t('admin.general.reserved') %></th> 
                <th><%= t('admin.general.published') %></th> 
                <th><%= t('admin.general.actions') %></th> 
            </tr>
        </thead>
        <tbody>
            <%= render :partial => "item", :collection => @pages %>
        </tbody>
    </table>
</div>


<header class="page_description">
    <h2><%= t('admin.pages.pages_tree') %></h2>
    <p><%= t('admin.pages.drag_pages_to_sort_them') %></p>
</header>
<div class="wrap cell_16"> 
    <div id='pages-tree'>
        <%= page_tree(@root_page) -%>
        <div class="buttons">
            <%= button_to_function t('admin.general.save'), "submit_tree()" %>
        </div>
    </div>

    <script type="text/javascript">
        function submit_tree(){
            serialized_tree = $('ol.sortable').nestedSortable('serialize');
            $.ajax({
                type: "POST",
                url: '/admin/pages/sort',
                data: { _method:'PUT', page: serialized_tree, admin_editing_language: '<%= @admin_editing_language %>' }
            });
        }
    </script>
</div>

app/views/admin/pages/new.html.erb
<%= content_for :title do %><%= t('admin.pages.new_page') %><% end %>

<header class="page_description">
    <h2><%= t('admin.pages.create_a_new_page') %></h2>
</header>

<section class="">
     <% unless @page.errors.blank? %>
     <div class="alert alert_red">
         <img height="24" width="24" src="/admin/images/icons/small/white/Alarm%20Bell.png">
         <%= t('admin.general.errors') %>: <%= errors_for @page %>
     </div>
     <% end %>
</section>

<div class="wrap cell_16">
    <%= form_for @page, :url => admin_pages_path, :html => { :multipart => true } do |f| %>
    <%= render :partial => "form", :object => @page, :as => :page, :locals => {:f => f, :lang => @admin_editing_language} %>

    <div class="buttons">
        <%= link_to t('admin.general.back'), admin_pages_url, :class => "submit" %>
        <%= submit_tag t('admin.general.save'), :class => "submit" %>    
    </div>
    <% end %>
</div>

app/views/admin/pages/set_editing_language.js.erb
window.location.reload();

app/views/admin/pages/show.html.erb
<%= content_for :title do %><%= t('admin.pages.manage_contents', :title => @page.title) %><% end %>

<header class="page_description">
    <h2>[<%= @page.lang %>] <%= t('admin.pages.manage_contents', :title => @page.title) %> - <%= link_to t("admin.pages.go_to_page_properties"), edit_admin_page_path(@page) %></h2>
</header>

<%= render :partial => "available_areas", :locals => {:current_layout => @current_layout, :snippets => @snippets, :page => @page} %>

<%= render :partial => "layout_selector", :locals => {:current_layout => @current_layout, :layouts => @layouts} %>

<%= render :partial => "available_snippets", :locals => {:snippets_available => @snippets_available} %>

<script type="text/javascript">
  <%= render :partial => "drag_drop.js", :locals => {:sorting_url => sort_admin_page_snippets_path(@page),
                                         :apply_layout_url => apply_layout_admin_page_path(@page) } %>
</script>

app/views/admin/pages/sort.js.erb
alert( "<%= @result %>" );

app/views/admin/pages/toggle.js.erb
if ('<%= @error %>'){
	alert("Something went wrong when you didn't expect it!");
}
else{
	$("#page_item_<%= @page.id %>").replaceWith('<%= escape_javascript(render(:partial => "item", :object => @page)) %>');
}