config/routes.rb
Railsyard2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => "site#show"
  themes_for_rails
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}
  
  match "/login" => redirect("/users/login")
  match "/logout" => redirect("/users/logout")
  match "/signup" => redirect("/users/signup")
  match "/admin" => redirect("/admin/pages")
  
  namespace :admin do 
    resources :pages do
      put 'sort', :on => :collection
      put 'set_editing_language', :on => :collection
      post 'toggle', :on => :member
      post 'apply_template', :on => :member
      put 'apply_layout', :on => :member
      get 'purge_limbo', :on => :member
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :users do
      post 'toggle', :on => :member
    end
    resources :articles do
      post 'toggle', :on => :member
    end
    resources :article_layouts do
      put 'apply_layout', :on => :member
      put 'set_editing_language', :on => :collection
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :categories do
      post 'quick_create', :on => :collection
    end
    resource :settings
    resources :uploads
    resources :comments do
      post 'toggle', :on => :member
    end
    resources :tags, :only => [:index]
  end
  
  resources :users
  resources :comments
  match ':lang/article/:year/:month/:day/:pretty_url' => 'articles#show', :as => 'show_article', :constraints => {:lang => $AVAILABLE_LANGUAGES, :year => /\d+/, :month => /\d+/, :day => /\d+/}
  match ':lang/feed' => 'articles#feed', :as => :feed, :defaults => { :format => 'atom' }

  match '/:lang' => "site#show", :constraints => {:lang => /[a-z]{2}/}
  scope "/:lang" do
    match "*page_url" => "site#show", :constraints => {:lang => /[a-z]{2}/}
  end
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at DESC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # Comments belong to a user, but not required
  belongs_to :user
  
  validates :email, :presence => true, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :username, :presence => true
  validates :body, :presence => true
  
  scope :published, where(:published => true)
  
  self.per_page = 10
  
  def publish
    update_attributes!(:published => true)
  end
  
  def unpublish
    update_attributes!(:published => false)
  end
  
  def toggle
    if !self.published
      self.publish
    else
      self.unpublish
    end
  end
  
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  
  ## manual authorization
  before_filter do |controller|
    controller.check_role("admin") unless (controller.action_name == "set_editing_language")
  end
  
  ## CanCan authorization - see Ability model
  authorize_resource
  skip_authorization_check :only => :set_editing_language
  
  def index
    @admin_editing_language = admin_editing_language
    @comments = Comment.all
  end
  
  def edit
    @admin_editing_language = admin_editing_language
    @comment = Comment.find params[:id]
  end

  def update
    @comment = Comment.find params[:id]
    @comment.attributes = params[:comment]

    if @comment.save && @comment.errors.empty? && params[:save_and_close]
      redirect_to admin_comments_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    if @comment && @comment.destroy && @comment.errors.empty?
      redirect_to admin_comments_path
    end
  end
  
  def toggle
    @comment = Comment.find(params[:id])
    @error = true unless @comment && @comment.toggle
    # Renders toggle.js.erb
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.published = true
    if @comment && verify_recaptcha(:model => @comment) && @comment.save && @comment.errors.empty?  
      if @comment.commentable_type == "Article"
        @article = Article.find(@comment.commentable_id)
        @commentable_url = get_article_url(@article)
      else
        #add your commentable here
        @commentable_url = "/"
      end
      respond_to do |format|
        format.js {
          render :js => "window.location = \"#{@commentable_url}\";"
        }
        format.html {
          redirect_to @commentable_url
        }
      end
    else
      respond_to do |format|
        format.js {
          render :js => "Recaptcha.reload(); alert('#{@comment.errors.full_messages.join("; ")}');"
        }
      end
    end
    
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_item.html.erb
<tr id='comment_item_<%= item.id %>'>
  <td>
    <%= link_to item.commentable.title, get_article_url(item.commentable) %>
  </td>
  <td>
    <%= item.username %>
  </td>
  <td>
    <%= item.body.truncate(60) %>
  </td>
  <td>
    <%= l item.updated_at, :format => :date_with_parenthesized_time %>
  </td>
  <td calss="center">
    <%= item.published ? t("admin.general.yes") : t("admin.general.no") %>
  </td>

  <td class="center">
    <%= link_to image_tag("../admin/images/icons/small/grey/Pencil.png"), edit_admin_comment_path(item) %>
    <%= link_to image_tag("../admin/images/icons/small/grey/View.png"), get_article_url(item.commentable, :anchor => "comment-#{item.id}"), :class => "submit", :target => '_blank' %>
    <%= link_to t("admin.general.toggle"), toggle_admin_comment_path(item), :remote => true, :method => :post %>
    <%= link_to t("admin.general.delete"), admin_comment_path(item), :class => 'icon-delete', :method => :delete, :confirm => t('admin.comments.are_you_sure_to_delete') %>
  </td>
</tr>

app/views/admin/comments/edit.html.erb
<%= content_for :title do %><%= t('admin.comments.comment') %><% end %>

<header class="page_description">
  <h2><%= t('admin.comments.comment') %></h2>
</header>

<div class="wrap cell_16">
  <%= form_for @comment, :url => admin_comment_path(@comment) do |f| %>
  <div class="wrap block">
    <div class="block">
      <%= f.label t("admin.general.title") %>
      <%= f.text_field :title %>
      
      <%= f.label t("admin.comments.comment") %>
      <%= f.text_area :body %>

      <%= f.label t("admin.general.author") %>
      <%= f.text_field :username %>

      <%= f.label t("admin.users.email") %>
      <%= f.text_field :email %>

      <%= f.label t("admin.comments.website") %>
      <%= f.text_field :website %>

      <%= f.label t("admin.comments.created_at") %>
      <%= l @comment.created_at, :format => :date_with_parenthesized_time %>

      <%= f.label t("admin.articles.article") %>
      <%= @comment.commentable.title %>

      <%= f.label t("admin.general.published") %>
      <%= f.check_box :published %>
      <%= t("admin.general.published") %>
    </div>
  </div>

  <div class="buttons">
    <%= link_to t('admin.general.delete'), admin_comment_path(@comment), :class => 'submit delete', :method => :delete, :confirm => t('admin.comments.are_you_sure_to_delete') %>
    <%= link_to t('admin.general.back'), admin_comments_url, :class => "submit" %>
    <%= link_to t('admin.general.view'), get_article_url(@comment.commentable, :anchor => "comment-#{@comment.id}"), :class => "submit", :target => '_blank' %>
    <%= submit_tag t('admin.general.save_and_close'), :class => "submit", :name => 'save_and_close' %>
  </div>

  <% end %>
</div>

app/views/admin/comments/index.html.erb
<%= content_for :title do %><%= t('admin.comments.comments_management') %><% end %>

<div class="lang_selector">
    <%= select_tag "language", options_from_collection_for_select(Language.all, 'short', 'name', @admin_editing_language),
        :onchange => "$.post('#{set_editing_language_admin_pages_path}', {'_method':'put', 'admin_editing_language':this.value} );" %>
</div>

<header class="page_description">
    <h2><%= t('admin.comments.comments_list') %></h2>
</header>

<div class="wrap cell_16 round_all">
    <table class="fancy_rows datatable">
        <thead>
            <tr>
                <th><%= t('admin.articles.article') %></th>
                <th><%= t('admin.general.author') %></th> 
                <th><%= t('admin.comments.comment') %></th>
                <th><%= t('admin.general.last_update') %></th>
                <th><%= t('admin.general.published') %></th>
                <th><%= t('admin.general.actions') %></th> 
            </tr>
        </thead>
        <tbody>
            <%= render :partial => "item", :collection => @comments %>
        </tbody>
    </table>
</div>

app/views/admin/comments/toggle.js.erb
if ('<%= @error %>'){
	alert("Something went wrong when you didn't expect it!");
}
else{
	$("#comment_item_<%= @comment.id %>").replaceWith('<%= escape_javascript(render(:partial => "item", :object => @comment)) %>');
}