config/routes.rb
Railsyard2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => "site#show"
  themes_for_rails
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}
  
  match "/login" => redirect("/users/login")
  match "/logout" => redirect("/users/logout")
  match "/signup" => redirect("/users/signup")
  match "/admin" => redirect("/admin/pages")
  
  namespace :admin do 
    resources :pages do
      put 'sort', :on => :collection
      put 'set_editing_language', :on => :collection
      post 'toggle', :on => :member
      post 'apply_template', :on => :member
      put 'apply_layout', :on => :member
      get 'purge_limbo', :on => :member
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :users do
      post 'toggle', :on => :member
    end
    resources :articles do
      post 'toggle', :on => :member
    end
    resources :article_layouts do
      put 'apply_layout', :on => :member
      put 'set_editing_language', :on => :collection
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :categories do
      post 'quick_create', :on => :collection
    end
    resource :settings
    resources :uploads
    resources :comments do
      post 'toggle', :on => :member
    end
    resources :tags, :only => [:index]
  end
  
  resources :users
  resources :comments
  match ':lang/article/:year/:month/:day/:pretty_url' => 'articles#show', :as => 'show_article', :constraints => {:lang => $AVAILABLE_LANGUAGES, :year => /\d+/, :month => /\d+/, :day => /\d+/}
  match ':lang/feed' => 'articles#feed', :as => :feed, :defaults => { :format => 'atom' }

  match '/:lang' => "site#show", :constraints => {:lang => /[a-z]{2}/}
  scope "/:lang" do
    match "*page_url" => "site#show", :constraints => {:lang => /[a-z]{2}/}
  end
  
  

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :title, :description, :published, :publish_at, :div_id, :div_class, :div_style, :area, :cell_controller, :cell_action, :handler, :options
  has_one :paste, :dependent => :destroy
  has_one :page, :through => :paste
  has_one :article_layout, :through => :paste
  has_many :snippet_components
  has_many :uploads, :as => :attachable, :dependent => :destroy
  accepts_nested_attributes_for :snippet_components
  
  validates_presence_of :title, :presence => true, :length => {:minimum => 3}
  
  serialize :options, Hash
  
  
  scope :published, :conditions => ["published = ?", true]
  scope :drafts, :conditions => ["published = ?", false]
  scope :for_area, lambda {|area| where("area = ?", area).order('pastes.position ASC')}
  
  def publish
    update_attributes!(:published => true, :publish_at => Time.now)
  end
  
  def unpublish
    update_attributes!(:published => false)
  end
  
  def toggle
    if !self.published
      self.publish
    else
      self.unpublish
    end
  end
  
  def self.available_for_pages
    cells = []
    search_cells.map do |cell_conf_file|
      cells << YAML.load_file(cell_conf_file)
    end
    cells_for_pages = cells.map{|c| c["cell"]} 
    cells_for_pages.delete_if{|d| d["class"] == "article"}
  end
  
  def self.available
    cells = []
    search_cells.map do |cell_conf_file|
      cells << YAML.load_file(cell_conf_file)
    end
    cells.map{|c| c["cell"]} 
  end
  
  def self.search_cells
    #cells_path = "#{Rails.root.to_s}/app/cells"
    files = Cell::Rails.view_paths.map { |p| p.to_s + '/*.yml' }
    Dir.glob(files).select do |file|
      File.readable?("#{file}")
    end.compact.uniq
  end
  
  def self.find_available(snip_controller, snip_action)
    found_snippet_controller = available.select{|av_snip_class| av_snip_class["class"].eql?(snip_controller)}
    found_snippet_action = found_snippet_controller[0]["actions"].select{|av_snip_action| av_snip_action["method"].eql?(snip_action)}
    found_snippet_action[0]
  end
  
  def serialized_attributes
    Snippet.find_available(self.cell_controller, self.cell_action)["serialized_attributes"]
  end
  
end

app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < Admin::AdminController

  ## manual authorization
  before_filter do |controller|
    controller.check_role("admin")
  end

  ## CanCan authorization - see Ability model
  authorize_resource

  def edit
    @snippet = Snippet.find(params[:id])
    if @snippet.serialized_attributes && @snippet.serialized_attributes.any? {|att| att[1].eql? "article_categories"}
      @categories = Category.all
    end
    respond_to do |format|
      format.html { render }
      format.dialog { render :layout => false }
    end
  end

  def update
    @snippet = Snippet.find(params[:id])
    @categories = Category.all
    if @snippet
      back_url = @snippet.article_layout ? edit_admin_article_layout_path(@snippet.article_layout.lang) : admin_page_path(@snippet.page.id)
      @snippet.attributes = params[:snippet]
      respond_to do |format|
        if @snippet.save && @snippet.errors.empty?
          format.html { params[:save_and_close] ? (redirect_to back_url) : (render :action => "edit") }
          format.dialog { render :text => "success", :status => 400 }
        else
          format.html { render :action => "edit" }
          format.dialog { render :text => "#{@snippet.errors.full_messages.each { |m| "<li>#{m}</li>"}.join('') }", :layout => false }
        end
      end
    end
  end

  ## Creation, sorting and moving between areas
  # TO-DO more efficient code. I'm rushing.
  def sort
    if params[:article_layout_id]
      @resource_snippets = ArticleLayout.find(params[:article_layout_id]).snippets
    elsif params[:page_id]
      @resource_snippets = Page.find(params[:page_id]).snippets
    end

    params[:areas].map do |area|
      unless area[1].blank?
        area_name = area[0]
        received_snippets = area[1].split(',')
        received_snippets.each_with_index do |rec_snip, position|
          # New snippet creation
          unless @resource_snippets.map{|snip| snip.handler}.include?(rec_snip) # checks if the snippet was already present on page
            rec_snip_class, rec_snip_action = rec_snip.split('%')[0], rec_snip.split('%')[1]
            available_snippet = Snippet.find_available(rec_snip_class, rec_snip_action) # search the received snippet in the available snippets
            @new_snippet = @resource_snippets.create :area => area_name,                    # and creates the real snippet for the area on db
                                                 :handler => rec_snip,
                                                 :title => available_snippet["name"],
                                                 :cell_action => available_snippet["method"],
                                                 :cell_controller => rec_snip_class
          end
          # Snippets sorting and area change
          current_snippet = @resource_snippets.find_by_handler(rec_snip)
          current_snippet.paste.update_attribute(:position, position+1)
          current_snippet.update_attribute(:area, area_name)
        end
      end
    end
    # Renders sort.js.erb
  end

  def purge
    #TO-DO empty trash bin (limbo)
  end

  def destroy
    @snippet = Snippet.find(params[:id])
    if @snippet
      respond_to do |format|
        if @snippet.destroy && @snippet.errors.empty?
          format.html { redirect_to admin_page_url( params[:page_id] ) }
          format.json { render :json => {} }
        else
          format.html { render :action => 'edit' }
          format.json { render :json => @snippet.errors.merge({ :message => 'There was an error!' }), :status => :unprocessable_entity }
        end
      end
    end
  end

end

app/helpers/admin/snippets_helper.rb
module Admin::SnippetsHelper
end

app/views/admin/snippets/_form.dialog.erb
<div class="box grid_16 round_all">
     <div class="">
         <div class="block">                
            <%= f.label :title, t('admin.general.title') %>
            <%= f.text_field :title, {:id=>"notempty", :title=>t("admin.general.field_cant_be_blank"), :class=>"large required", :autofocus=>""} %>

            <%= f.fields_for :options do |o| %>
                <% if @snippet.serialized_attributes %>
                    <% @snippet.serialized_attributes.map do |att| %>
                        <% default_value = @snippet.options.blank? ? "" : @snippet.options[att[0]] %>     
                        <%= o.label att[0] %>                  
                        <% case att[1] %>
                            <% when "string" then %>
                                <%= o.text_field att[0], :value => default_value, "data-validation" => "text" %>
                            <% when "text" then %>
                                <%= o.text_area att[0], :value => default_value, "data-validation" => "text" %>
                            <% when "integer" then %>
                                <%= o.text_field att[0], :value => default_value, "data-validation" => "integer" %>
                            <% when "editor" then %>
                                <%= o.cktext_area att[0], :input_html => { :value => default_value, "data-validation" => "none" } %>
                            <% when "article_categories" then %>
                                <%# Needed to submit the serialized form when no category is choosen %>
                                <div><input type="hidden" type="checkbox" value="0" name="snippet[options][categories][]"></div>
                                <% @categories.map do |category| %> 
                                <div>
                                    <%= check_box_tag "snippet[options][#{att[0]}][]", category.id, default_value.include?(category.id.to_s) %>  
                                    <%= category.name.humanize %>
                                </div>
                                <% end %>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>    
</div>

app/views/admin/snippets/_form.html.erb
<div class="box grid_16 round_all">
     <div class="">
         <div class="block">                
            <%= f.label :title, t('admin.general.title') %>
            <%= f.text_field :title, {:id=>"notempty", :title=> t("admin.general.field_cant_be_blank"), :class=>"large required", :autofocus=>""} %>

            <%= f.fields_for :options do |o| %>
                <% if @snippet.serialized_attributes %>
                    <% @snippet.serialized_attributes.map do |att| %>
                        <% default_value = @snippet.options.blank? ? "" : @snippet.options[att[0]] %>     
                        <%= o.label att[0] %>                  
                        <% case att[1] %>
                            <% when "string" then %>
                                <%= o.text_field att[0], :value => default_value, "data-validation" => "text" %>
                            <% when "text" then %>
                                <%= o.text_area att[0], :value => default_value, "data-validation" => "text" %>
                            <% when "integer" then %>
                                <%= o.text_field att[0], :value => default_value, "data-validation" => "integer" %>
                            <% when "editor" then %>
                                <%### SINTAX ERROR BUG IN EDITOR JS, I need to hardcode the form %>
                                <%### original: %>
                                <%#= o.cktext_area att[0], :input_html => { :value => default_value, "data-validation" => "none" } %>
                                <%### hardcoded: %>
                                <% if true %>
                                <textarea cols="40" id="snippet_options_body" name="snippet[options][body]" rows="20">
                                    <%= default_value %>
                                </textarea>
                                <script type="text/javascript">
                                    if (CKEDITOR.instances['snippet_options_<%= att[0] %>']) {CKEDITOR.remove(CKEDITOR.instances['snippet_options_<%= att[0] %>']);}CKEDITOR.replace('snippet_options_<%= att[0] %>', { "language": 'en' });
                                </script>
                                <% end %>
                                <%### end hardcoded %>
                            <% when "article_categories" then %>
                                <%# Needed to submit the serialized form when no category is choosen %>
                                <div><input type="hidden" type="checkbox" value="0" name="snippet[options][categories][]"></div>
                                <% @categories.map do |category| %> 
                                <div>
                                    <%= check_box_tag "snippet[options][#{att[0]}][]", category.id, default_value.include?(category.id.to_s), :id => "category_#{category.name.underscore}" %>  
                                    <%= category.name.humanize %>
                                </div>
                                <% end %>
                            <% when "uploads" then %>
                                <%# Hack to avoid form inside form. Calls uploads/new via ajax %>
                                <script type='text/javascript'>
                                    $(document).ready(function() {                              
                                        $.ajax({
                                            type: 'get',
                                            url: '<%= new_admin_upload_path(:attachable_id => @snippet.id, :attachable_type => @snippet.class) %>',
                                            dataType: 'script'
                                        });
                                    });
                                </script>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>    
</div>

app/views/admin/snippets/_upload_panel.html.erb
<!-- TEST AREA - NOT FOR PRODUCTION -->
<div class="cell_13">
    <div id="upload-test">
        <div id="fileupload">
            <%= form_for Upload.new, :url => admin_uploads_path, :html => { :multipart => true } do |f| %>
                <div class="fileupload-buttonbar">
                    <label class="fileinput-button">
                        <span>Add files...</span>
                                <%= f.file_field :data %>
                    </label>
                    <!-- <button type="submit" class="start">Start upload</button> -->
                    <button type="reset" class="cancel">Cancel upload</button>
                    <!-- <button type="button" class="delete">Delete files</button> -->
                </div>
            <% end %>
            <div class="fileupload-content">
                <table class="files"></table>
                <div class="fileupload-progressbar"></div>
            </div>
        </div>

        <script id="template-upload" type="text/x-jquery-tmpl">
            <tr class="template-upload{{if error}} ui-state-error{{/if}}">
                <td class="preview"></td>
                <td class="name">${name}</td>
                <td class="size">${sizef}</td>
                {{if error}}
                    <td class="error" colspan="2">Error:
                        {{if error === 'custom_failure'}}Custom Error Message
                        {{else}}${error}
                        {{/if}}
                    </td>
                {{else}}
                    <td class="progress"><div></div></td>
                    <td class="start"><button>Start</button></td>
                {{/if}}
                <td class="cancel"><button>Cancel</button></td>
            </tr>
        </script>
        <script id="template-download" type="text/x-jquery-tmpl">
            <tr class="template-download{{if error}} ui-state-error{{/if}}">
                {{if error}}
                    <td></td>
                    <td class="name">${name}</td>
                    <td class="size">${sizef}</td>
                    <td class="error" colspan="2">Error:
                        {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
                        {{else}}${error}
                        {{/if}}
                    </td>
                {{else}}
                    <td class="preview">
                        {{if thumbnail_url}}
                            <a href="${url}" target="_blank"><img src="${thumbnail_url}"></a>
                        {{/if}}
                    </td>
                    <td class="name">
                        <a href="${url}"{{if thumbnail_url}} target="_blank"{{/if}}>${name}</a>
                    </td>
                    <td class="size">${sizef}</td>
                    <td colspan="2"></td>
                {{/if}}
                <td class="delete">
                    <button data-type="${delete_type}" data-url="${delete_url}">Delete</button>
                </td>
            </tr>
        </script>

        <script type="text/javascript" charset="utf-8">
            $(function () {
                // Initialize the jQuery File Upload widget:
                $('#fileupload').fileupload();
                // 
                // Load existing files:
                $.getJSON($('#fileupload form').prop('action'), function (files) {
                    var fu = $('#fileupload').data('fileupload');
                    fu._adjustMaxNumberOfFiles(-files.length);
                    fu._renderDownload(files)
                        .appendTo($('#fileupload .files'))
                        .fadeIn(function () {
                            // Fix for IE7 and lower:
                            $(this).show();
                        });
                });

                // Open download dialogs via iframes,
                // to prevent aborting current uploads:
                $('#fileupload .files a:not([target^=_blank])').live('click', function (e) {
                    e.preventDefault();
                    $('<iframe style="display:none;"></iframe>')
                        .prop('src', this.href)
                        .appendTo('body');
                });

            });
        </script>
        
    </div><!-- end upload test -->         
</div><!-- end cell_13 -->

app/views/admin/snippets/edit.dialog.erb
<div class="popup">
    <% destination = @snippet.article_layout ? admin_article_layout_snippet_path(@snippet.article_layout.id, @snippet.id, :format => :dialog) : admin_page_snippet_path(@snippet.page.id, @snippet.id, :format => :dialog) %>
    <%= form_for @snippet, :url => destination, :html => { :multipart => true } do |f| %>
    <%= errors_for(@snippet) %>
    <%= render :partial => "form", :object => @article, :locals => {:f => f} %>

    <div class="buttons">
        <%= submit_tag t('admin.general.save'), :class => "submit" %>
    </div>
    <% end %>
</div>

app/views/admin/snippets/edit.html.erb
<header class="page_description">
    <h2><%= t('admin.snippets.edit_snippet', :title => @snippet.title) %></h2>
    <% unless @snippet.errors.blank? %>
    <div class="alert alert_red">
        <img height="24" width="24" src="/admin/images/icons/small/white/Alarm%20Bell.png">
        <%= t('admin.general.errors') %>: <%= errors_for @snippet %>
    </div>
    <% end %>
</header>

<div class="wrap cell_16">
    <% destination = @snippet.article_layout ? admin_article_layout_snippet_path(@snippet.article_layout.id, @snippet.id) : admin_page_snippet_path(@snippet.page.id, @snippet.id) %>
    <% back_url = @snippet.article_layout ? edit_admin_article_layout_path(@snippet.article_layout.lang) : admin_page_path(@snippet.page.id) %>
    <%= form_for @snippet, :url => destination, :html => { :multipart => true } do |f| %>
        <%= errors_for(@snippet) %>
        <%= render :partial => "form", :object => @article, :locals => {:f => f} %>
        
        <div class="buttons">
            <%= link_to t('admin.general.delete'), destination, :method => :delete, :confirm => t('admin.pages.are_you_sure_to_delete', :name => @snippet.title), :class => "submit delete"  %>
            <%= link_to t('admin.general.back'), back_url, :class => "submit" %>
            <%= submit_tag t('admin.general.save'), :class => "submit" %>   
            <%= submit_tag t('admin.general.save_and_close'), :class => "submit", :name => 'save_and_close' %>  
        </div>
    <% end %>
    <div id='uploader-placeholder'>
        
    </div>
</div>

app/views/admin/snippets/sort.js.erb
<% if @new_snippet %>
	<% destination = @new_snippet.article_layout ? edit_admin_article_layout_snippet_path(@new_snippet.article_layout.id, @new_snippet.id) : edit_admin_page_snippet_path(@new_snippet.page.id, @new_snippet.id) %>
	<% delete_destination = @new_snippet.article_layout ? admin_article_layout_snippet_path(@new_snippet.article_layout.id, @new_snippet.id) : admin_page_snippet_path(@new_snippet.page.id, @new_snippet.id) %>
	
	snip = jQuery(document.getElementById('<%= @new_snippet.handler %>'))
	snip.append("<%= escape_javascript(link_to '<span>edit</edit>'.hs, destination, :class => 'icon edit') %>")
	snip.append("<%= escape_javascript(link_to '<span>delete</span>'.hs, delete_destination, :method => :delete, :confirm => t('admin.pages.are_you_sure_to_delete', :name => @new_snippet.title), :class => 'icon delete') %>")
	snip.addClass("active_widget");
	snip.find('h2').html("<%= truncate(@new_snippet.title, :length => 23, :omission => '...') %>");
	
<% end %>