config/routes.rb
Railsyard2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => "site#show"
  themes_for_rails
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}
  
  match "/login" => redirect("/users/login")
  match "/logout" => redirect("/users/logout")
  match "/signup" => redirect("/users/signup")
  match "/admin" => redirect("/admin/pages")
  
  namespace :admin do 
    resources :pages do
      put 'sort', :on => :collection
      put 'set_editing_language', :on => :collection
      post 'toggle', :on => :member
      post 'apply_template', :on => :member
      put 'apply_layout', :on => :member
      get 'purge_limbo', :on => :member
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :users do
      post 'toggle', :on => :member
    end
    resources :articles do
      post 'toggle', :on => :member
    end
    resources :article_layouts do
      put 'apply_layout', :on => :member
      put 'set_editing_language', :on => :collection
      resources :snippets do
        put 'sort', :on => :collection
        post 'toggle', :on => :member
      end
    end
    resources :categories do
      post 'quick_create', :on => :collection
    end
    resource :settings
    resources :uploads
    resources :comments do
      post 'toggle', :on => :member
    end
    resources :tags, :only => [:index]
  end
  
  resources :users
  resources :comments
  match ':lang/article/:year/:month/:day/:pretty_url' => 'articles#show', :as => 'show_article', :constraints => {:lang => $AVAILABLE_LANGUAGES, :year => /\d+/, :month => /\d+/, :day => /\d+/}
  match ':lang/feed' => 'articles#feed', :as => :feed, :defaults => { :format => 'atom' }

  match '/:lang' => "site#show", :constraints => {:lang => /[a-z]{2}/}
  scope "/:lang" do
    match "*page_url" => "site#show", :constraints => {:lang => /[a-z]{2}/}
  end
  
  

end

app/models/layout.rb
class Layout
  include SimpleModel
  attributes :title, :view, :areas
  validates :title, :presence => true
  validates :view, :presence => true
end

app/views/layouts/_frontend_controls.html.erb
<% if has_frontend_controls? %>
  <%= stylesheet_link_tag :all %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
  <%= javascript_include_tag 'jquery_ujs' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag '/admin/javascripts/jquery.form.js' %>
  <%= javascript_include_tag :ckeditor %>
  
  <div id="yd_dialog" style="display: none;">
    <notice class="error" style="display: none;"></notice>
    <div id="yd_dialog_content"></div>
    <div class="loading"><span>Loading data, please wait!</span></div>
  </div>
  
  <%
    if @page
      admin_snippet_sort_url = "/admin/pages/#{@page.id}/snippets/sort"
    elsif @article_layout
      admin_snippet_sort_url = sort_admin_article_layout_snippets_path(@article_layout)
    end 
  %>
  <%= javascript_tag <<-JAVASCRIPT
  var admin_snippet_sort_url = '#{admin_snippet_sort_url}';
  $(document).ready(function() {
    adminInitSnippetSortable();
  });
  JAVASCRIPT
  %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Raylsyard CMS Admin Panel">
    <meta name="author" content="Cantiere Creativo @teamcantiere - Silvio Relli @silviorelli - Matteo Papadopoulos @spleenteo">
    <meta name="generator" content="Ruby on Rails" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <link rel="shortcut icon" href="/favicon.ico">
    
    <!-- will render the page using Google Chrome rather than Internet Explorer -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= t "admin.general.railsyard_admin_panel" %> - <%= yield :title %></title>        
    
    <%= stylesheet_link_tag "/admin/stylesheets/all.css" %>
    <%= stylesheet_link_tag('jquery.fileupload-ui') %>    
    <!--[if IE 6]><link rel="stylesheet" type="text/css" href="/admin/stylesheets/ie6.css" media="screen" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" href="/admin/stylesheets/ie.css" media="screen" /><![endif]-->
    
    <%= javascript_include_tag "jquery.min",
                               "jquery-ui.min",
                               "jquery.tmpl.min",
                               "jquery_ujs",
                               "/admin/javascripts/jquery.livequery.js",
                               "/admin/javascripts/jquery.ui.nestedSortable.js",
                               "/admin/javascripts/livevalidation/livevalidation_standalone.js",
                               "/admin/javascripts/tipsy/jquery.tipsy.js",
                               "/admin/javascripts/uitotop/js/jquery.ui.totop.js",
                               "/admin/javascripts/DataTables/jquery.dataTables.min.js",
                               "/admin/javascripts/jquery.iframe-transport.js",
                               "/admin/javascripts/jquery.fileupload.js",
                               "/admin/javascripts/jquery.fileupload-ui.js",
                               "/admin/javascripts/modernizr.js",
                               "/admin/javascripts/application.js"
    %>
    <%= javascript_include_tag :ckeditor %>
    
    <%= yield :extra_header %>
    <%= csrf_meta_tag %>
</head>
<body>
    <div class="hive_16 clearfix">
        <div class="cell_3">
            <aside id="left_bar">
                <a href="/admin" class="logo"><span>Railsyard CSM</span></a>
                <section class="user clearfix">
                    <h3><%= current_user.email %></h3>
                    <%= gravatar_image_tag(current_user.email, :alt => current_user, :width=>"55px") %>
                    <div class="user_details">
                        <% if current_user.is_admin? %>
                            <h2><%= t "admin.general.administrator" %></h2>
                        <% end %>
                        <ul>
                            <li><%= link_to t('admin.general.profile'), edit_admin_user_path(current_user) %> <span class="divider">|</span></li>
                            <li><%= link_to t('admin.general.logout'), logout_path() %></li>
                        </ul>
                    </div>
                </section><!-- #user_wrap -->
                
                <form id="aside_search"><input class="round_all" type="text" value="Search" onclick="value=''"></form>

                <ul id="accordion">
                    <!--
                    <li><a class="top_level"><img src="/admin/images/icons/small/grey/Home.png"/>Home</a>
                        <ul class="drawer">
                            <li><a href="/admin"><%#= t('admin.general.admin_dashboard') %></a></li>
                            <li><a href="/" target="_blank"><%#= t('admin.general.public_site') %></a></li>
                        </ul>
                    </li>
                    -->
                    <% if can? :manage, Page %>
                    <li><a <%= set_class(:class => "top_level", :controller => "pages") %>><img src="/admin/images/icons/small/grey/Documents.png"/><%= t('admin.pages.pages') %></a>
                        <ul class="drawer">
                            <li <%= set_class(:controller => "pages", :action => "index") %>><%= link_to t('admin.general.list'), admin_pages_path() %></li>
                            <li <%= set_class(:controller => "pages", :action => "new") %>><%= link_to t('admin.general.new'), new_admin_page_path() %></li>
                            <!-- <li <%#= set_class("pages", "preset") %>><a href="#">Preset</a></li> -->
                        </ul>
                    </li>
                    <% end %>
                    <% if can? :manage, Article %>
                    <li><a <%= set_class(:class => "top_level", :controller => ["articles","article_layouts","comments"]) %>><img src="/admin/images/icons/small/grey/Write.png"/><%= t('admin.articles.articles') %></a>
                        <ul class="drawer">
                            <li <%= set_class(:controller => "articles", :action => "index") %>><%= link_to t('admin.general.list'), admin_articles_path() %></li>
                            <li <%= set_class(:controller => "articles", :action => "new") %>><%= link_to t('admin.general.new'), new_admin_article_path() %></li>
                            <li <%= set_class(:controller => "article_layouts", :action => "edit") %>><%= link_to t('admin.general.design'), edit_admin_article_layout_path(@admin_editing_language) %></li>
                            <li <%= set_class(:controller => "categories", :action => "index") %>><%= link_to t('admin.categories.categories'), admin_categories_path %></li>
                            <li <%= set_class(:controller => "comments", :action => "index") %>><%= link_to t('admin.comments.comments'), admin_comments_path %></li>
                            
                        </ul>
                    </li>
                    <% end %>
                    <% if can? :manage, User %>
                    <li><a <%= set_class(:class => "top_level", :controller => ["users"]) %>><img src="/admin/images/icons/small/grey/Users.png"/><%= t('admin.users.users') %></a>
                        <ul class="drawer">
                            <li <%= set_class(:controller => "users", :action => "index") %>><%= link_to t('admin.general.list'), admin_users_path %></li>
                            <li <%= set_class(:controller => "users", :action => "new") %>><%= link_to t('admin.general.new'), new_admin_user_path %></li>
                            <!-- <li><a href="#">Esporta</a></li> -->
                        </ul>
                    </li>
                    <% end %>
                    <% if can? :manage, Setting %>
                    <li><a <%= set_class(:class => "top_level", :controller => ["settings"]) %>><img src="/admin/images/icons/small/grey/Cog%202.png"/><%= t('admin.settings.settings') %></a>
                        <ul class="drawer">
                            <li <%= set_class(:controller => "settings", :action => "edit") %>><%= link_to t('admin.general.general'), edit_admin_settings_path %></li>
                            <!-- <li <%#= set_class(:controller => "users", :action => "index") %>><%#= link_to "Il tuo profilo", edit_admin_user_path(current_user) %></li> -->
                        </ul>
                    </li>
                    <% end %>
                    <% if false %>
                    <li><a class="top_level"><img src="/admin/images/icons/small/grey/Paperclip.png"/>Media</a>
                        <ul class="drawer">
                            <li><a href="#">Tutti</a></li>
                            <li><a href="#">Immagini</a></li>
                            <li><a href="#">Documenti</a></li>
                            <li><a href="#">Video</a></li>
                            <li><a href="#">Audio</a></li>
                        </ul>
                    </li>
                    <% end %>
                </ul>
                <script type="text/javascript">
                    $(document).ready(function(){
                        $(function(){
                          /*
                           * Si apre l'accordion se un elemento
                           * ha sia la classe this_controller che top_level
                           */
                          var top_level = $(".this_controller.top_level");
                          var i = top_level.parent().prevAll().length;
                          $("#accordion").accordion({active: i});
                          
                          /*
                           * indivuo l'oggetto con classe this_action
                           * per mettere il trinagolo al lato della barra
                           */
                          var basic_tr = $("#left_bar > .menu_triangle");
                          basic_tr.clone().appendTo(".this_controller.this_action");
                          basic_tr.remove();
                          var tr = $(".menu_triangle", ".ui-accordion-content-active");
                          tr.css({"display": "block" });
                        });
                    });
                </script>
                
                <ul id="side_links" class="text_shadow" >
                    <li><%= link_to t('admin.general.documentation'), "https://github.com/cantierecreativo/railsyardcms/wiki", :target=>"_blank" %></li>
                    <li><%= link_to t('admin.general.updates_on_railsyard'), "http://twitter.com/teamcantiere", :target=>"_blank" %></li>
                    <li><%= link_to t('admin.general.sourcecode_on_github'), "https://github.com/cantierecreativo/railsyardcms", :target=>"_blank" %></li>
                    <li><%= link_to t('admin.general.cantiere_creativo'), "http://www.cantierecreativo.net", :target=>"_blank" %></li>
                </ul>
                <div class="menu_triangle"></div>
            </aside><!-- #sidebar -->
        </div>
        
        <div class="cell_13">
            <div id="main_container" class="clearfix">
                <%= yield %>
            </div>            
        </div>
        
        
    </div><!-- #wrapper -->
    <div class="hive_16">
        <footer id="template_options" class="clearfix">
            Railsyard CMS &bull; v.0.2.0 &bull; <a href="http://www.cantierecreativo.net">credits</a>
        </footer>
    </div>
    
</body>
</html>

app/views/layouts/admin_login.html.erb
<!DOCTYPE html>
<html dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Raylsyard CMS admininistration">
    <meta name="author" content="Cantiere Creativo @teamcantiere - Silvio Relli @silviorelli - Matteo Papadopoulos @spleenteo">

    <link rel="shortcut icon" href="/favicon.ico">

    <!-- will render the page using Google Chrome rather than Internet Explorer -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= t "admin.general.railsyard_admin_panel" %> - <%= yield :title %></title>

    <%= stylesheet_link_tag "/admin/stylesheets/all.css" %>

    <!--[if IE 6]><link rel="stylesheet" type="text/css" href="/admin/stylesheets/ie6.css" media="screen" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" href="/admin/stylesheets/ie.css" media="screen" /><![endif]-->


    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
    <%= javascript_include_tag 'jquery_ujs' %>

    <%= javascript_include_tag "/admin/javascripts/jquery.livequery.js",
                               "/admin/javascripts/application.js"
    %>
    <%= yield :extra_header %>
    <%= csrf_meta_tag %>
</head>
<html>
    <body>
        <div class="hive_16 clearfix">
            <div class="cell_3">
                <aside id="left_bar">
                    <a href="/admin" class="logo"><span>Railsyard CSM</span></a>
                    <section class="user clearfix">
                        <div class="login_box">
                          <%= yield %>
                        </div>
                    </section>
                </aside>
            </div>
        </div>
    </body>
</html>